[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]
options = [
  "-i",
  "2",   # indent 2
  "-s",  # simplify the code
  "-w",  # write back to the file
]

[formatter.golang]
command = "gofumpt"
includes = ["*.go"]
excludes = ["pkg/slice_operations/*"] # doesnt work for some reason
options = [
  "-w",     # write to file
  "--extra" # more rules
]